import { z } from "zod";

/**
 * Contract for content/projects.json (GENERATED by scripts/optimize-images.ts —
 * hand edits go in content/overrides.json and content/alt-overrides.json).
 */
export const MEDIA_ID = /^6af838_[0-9a-f]{32}$/;

export const ImageSchema = z.object({
  file: z.string().regex(/^\/(projects|site|blog)\/[a-z0-9-]+\/[a-z0-9-]+\.webp$|^\/(site|blog)\/[a-z0-9-]+\.webp$/),
  mediaId: z.string().regex(MEDIA_ID),
  sourceUrl: z.string().url().startsWith("https://static.wixstatic.com/media/"),
  width: z.number().int().positive(),
  height: z.number().int().positive(),
  originalWidth: z.number().int().positive(),
  originalHeight: z.number().int().positive(),
  blurDataURL: z.string().startsWith("data:image/webp;base64,"),
  /** Describes the space. May contain a {{TODO: …}} token until authored. */
  alt: z.string().min(1),
  caption: z.string().nullable(),
  focalPoint: z.tuple([z.number(), z.number()]).nullable(),
  role: z.enum(["cover", "gallery"]),
  source: z.enum(["warmup", "dom-only"]),
});

export const ImageRefSchema = z.object({ slug: z.string(), mediaId: z.string().regex(MEDIA_ID) });

export const CategorySchema = z.enum(["Residential", "Hospitality", "Wellness", "Commercial", "Education"]);

export const ProjectSchema = z
  .object({
    slug: z.string().regex(/^[a-z0-9-]+$/),
    title: z.string().min(1),
    category: CategorySchema.nullable(),
    categorySource: z.enum(["site", "override", "none"]),
    categoryNote: z.string().nullable().default(null),
    description: z.string().min(1),
    sourceUrl: z.string().url(),
    order: z.number().int().nonnegative(),
    /** Index into images[] used for the tile, the case-study hero and OG image. null when no images. */
    cover: z.number().int().nonnegative().nullable(),
    published: z.boolean().default(true),
    images: z.array(ImageSchema),
  })
  .refine((p) => p.cover === null || p.cover < p.images.length, { message: "cover index out of range" });

export const SiteImageSchema = ImageSchema.omit({ role: true, source: true });

export const MaterialSchema = z.object({
  id: z.string(),
  label: z.string(),
  /** Verbatim quote from scraped copy describing the material sensibility. */
  quote: z.string(),
  quoteSource: z.string().url(),
  image: ImageRefSchema.nullable(),
  objectPosition: z.string().default("50% 50%"),
});

export const ProjectsFileSchema = z.object({
  _generated: z.string(),
  generatedAt: z.string(),
  source: z.literal("https://www.stylemyspacedesign.com"),
  projects: z.array(ProjectSchema).min(1),
  home: z.object({
    /** Live-site h1, verbatim. */
    headline: z.string(),
    hero: ImageRefSchema.nullable(),
    manifesto: ImageRefSchema.nullable(),
    materials: z.array(MaterialSchema),
    meetTheDesigner: z.object({
      heading: z.string(),
      role: z.string(),
      name: z.string(),
      bio: z.array(z.string()),
      pressMention: z.string().nullable(),
      pressConfirmed: z.boolean(),
      portrait: SiteImageSchema.nullable(),
    }),
    /** The live site's three category cards, verbatim. */
    liveCards: z.array(z.object({ label: z.string(), title: z.string(), body: z.string() })),
    recentProjects: z.array(z.string()),
  }),
  portfolio: z.object({ title: z.string(), intro: z.string() }),
  blog: z.array(
    z.object({
      slug: z.string(),
      title: z.string(),
      excerpt: z.string(),
      readTime: z.string().nullable(),
      publishedAt: z.string(),
      author: z.string(),
      sourceUrl: z.string().url(),
      cover: SiteImageSchema.nullable(),
      body: z.array(z.object({ type: z.enum(["h2", "h3", "p", "li"]), text: z.string() })).nullable(),
    }),
  ),
  /** Live "Book Online" offerings, verbatim. */
  consultations: z.array(
    z.object({ name: z.string(), duration: z.string(), price: z.string().nullable(), sourceUrl: z.string().url() }),
  ),
  site: z.object({
    legalName: z.string().nullable(),
    emailDisplayed: z.string().email(),
    emailMailto: z.string().email().nullable(),
    phone: z.string().nullable(),
    showPricing: z.boolean(),
  }),
  /** Every {{TODO}} token present in this file, auto-collected. */
  todos: z.array(z.object({ token: z.string(), path: z.string() })),
});

export type ProjectsFile = z.infer<typeof ProjectsFileSchema>;
export type Project = z.infer<typeof ProjectSchema>;
export type ProjectImage = z.infer<typeof ImageSchema>;
export type SiteImage = z.infer<typeof SiteImageSchema>;
export type ImageRef = z.infer<typeof ImageRefSchema>;
export type Material = z.infer<typeof MaterialSchema>;
export type Category = z.infer<typeof CategorySchema>;
