/**
 * Image optimisation + content generation.
 *
 *   pnpm content:images [--force] [--only=<slug>]
 *
 * Inputs (read-only): content/scrape/pages/<slug>.json + scrape-report.json (from scripts/scrape.ts), the raw
 * originals under content/raw/**, content/overrides.json and content/alt-overrides.json (lead-authored).
 *
 * Outputs (owned by this script):
 *   public/projects/<slug>/NN-<hex>.webp   WebP master (long edge ≤ 2400, q82) per project image, NN = page order
 *   public/projects/<slug>/og.jpg          1200×630 OG crop of the cover
 *   public/site/portrait.webp              Meet-the-Designer portrait, public/site/og-home.jpg from overrides.home.hero
 *   public/blog/<postslug>.webp            blog covers
 *   content/projects.json                  validated against src/lib/content.schema.ts (ProjectsFileSchema)
 *   content/scrape/image-manifest.json     mediaId → { rawSha1, settingsHash, outputs[] } for idempotent reruns
 *   qa/contact-sheets/images/<slug>.png    labelled thumbnails for alt-text authoring (+ site.png)
 *
 * Nothing is invented: missing content is logged (and, for alt text, left as a {{TODO: …}} token collected in todos[]).
 * The file name uses the 32-hex part of the media id because ImageSchema.file forbids "_" in path segments.
 */
import { createHash } from "node:crypto";
import { createReadStream } from "node:fs";
import { mkdir, readFile, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";
import { z } from "zod";
import {
  CategorySchema,
  ImageRefSchema,
  MaterialSchema,
  ProjectsFileSchema,
  type ImageRef,
  type Project,
  type ProjectImage,
  type ProjectsFile,
  type SiteImage,
} from "../src/lib/content.schema";
import { makeContactSheet } from "./contact-sheet";
import { createLogger, errorMessage } from "./lib/log";
import { pLimit } from "./lib/plimit";

// ----------------------------------------------------------------------------
// Paths, settings, args
// ----------------------------------------------------------------------------

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SITE_URL = "https://www.stylemyspacedesign.com" as const;
const SCRAPE_DIR = path.join(ROOT, "content", "scrape");
const PAGES_DIR = path.join(SCRAPE_DIR, "pages");
const MANIFEST_FILE = path.join(SCRAPE_DIR, "image-manifest.json");
const PUBLIC_DIR = path.join(ROOT, "public");
const CONTENT_FILE = path.join(ROOT, "content", "projects.json");
const OVERRIDES_FILE = path.join(ROOT, "content", "overrides.json");
const ALT_OVERRIDES_FILE = path.join(ROOT, "content", "alt-overrides.json");
const SHEETS_DIR = path.join(ROOT, "qa", "contact-sheets", "images");

const SETTINGS = {
  master: { maxEdge: 2400, format: "webp", quality: 82, effort: 5, rotate: true },
  blur: { width: 16, format: "webp", quality: 20 },
  og: { width: 1200, height: 630, fit: "cover", position: "attention", format: "jpeg", quality: 80, mozjpeg: true },
  version: 1,
} as const;

const sha1 = (s: string) => createHash("sha1").update(s).digest("hex");
const MASTER_HASH = sha1(JSON.stringify({ master: SETTINGS.master, blur: SETTINGS.blur, v: SETTINGS.version }));
const OG_HASH = sha1(JSON.stringify({ og: SETTINGS.og, v: SETTINGS.version }));

const GENERATED_NOTE =
  "GENERATED by scripts/optimize-images.ts — do not edit; use content/overrides.json and content/alt-overrides.json";

const log = createLogger("images");

interface Args {
  force: boolean;
  only: string | null;
}

function parseArgs(argv: string[]): Args {
  const args: Args = { force: false, only: null };
  for (const a of argv) {
    if (a === "--force") args.force = true;
    else if (a.startsWith("--only=")) args.only = a.slice(7) || null;
    else throw new Error(`unknown argument ${a}`);
  }
  return args;
}

// ----------------------------------------------------------------------------
// Input contracts (subset of the scraper's output that this script consumes)
// ----------------------------------------------------------------------------

const ScrapeImageSchema = z.object({
  mediaId: z.string(),
  file: z.string(),
  ext: z.string(),
  sourceUrl: z.string(),
  originalWidth: z.number().nullable(),
  originalHeight: z.number().nullable(),
  caption: z.string().nullable(),
  description: z.string().nullable().optional(),
  alt: z.string().nullable().optional(),
  focalPoint: z.tuple([z.number(), z.number()]).nullable(),
  role: z.string(),
  source: z.string(),
  index: z.number().int(),
  postSlug: z.string().optional(),
  download: z
    .object({
      path: z.string(),
      bytes: z.number(),
      sha1: z.string(),
      width: z.number().nullable(),
      height: z.number().nullable(),
    })
    .nullable(),
});
type ScrapeImage = z.infer<typeof ScrapeImageSchema>;

const TextBlockSchema = z.object({
  tag: z.string(),
  text: z.string(),
  y: z.number(),
  inFooter: z.boolean(),
  inHeader: z.boolean(),
});
type TextBlock = z.infer<typeof TextBlockSchema>;

const BlogCardSchema = z.object({
  title: z.string(),
  href: z.string(),
  excerpt: z.string().nullable(),
  readTime: z.string().nullable(),
  author: z.string().nullable(),
  date: z.string().nullable(),
});

const ServiceCardSchema = z.object({
  title: z.string(),
  href: z.string().nullable(),
  duration: z.string().nullable(),
  price: z.string().nullable(),
});

const ScrapePageSchema = z.object({
  slug: z.string(),
  url: z.string(),
  kind: z.string(),
  status: z.number(),
  text: z.object({
    title: z.string().nullable(),
    meta: z.object({
      description: z.string().nullable(),
      publishedTime: z.string().nullable().optional(),
    }),
    h1: z.array(z.string()),
    textBlocks: z.array(TextBlockSchema),
    category: z.string().nullable(),
    links: z.object({ mailto: z.array(z.string()).optional() }).optional(),
    blogCards: z.array(BlogCardSchema).nullable().optional(),
    serviceCards: z.array(ServiceCardSchema).nullable().optional(),
    post: z
      .object({
        title: z.string().nullable(),
        author: z.string().nullable(),
        date: z.string().nullable(),
        readTime: z.string().nullable(),
        blocks: z.array(z.object({ tag: z.string(), text: z.string() })),
      })
      .nullable()
      .optional(),
  }),
  description: z.object({ chosen: z.string().nullable() }).nullable(),
  images: z.array(ScrapeImageSchema),
});
type ScrapePage = z.infer<typeof ScrapePageSchema>;

const ScrapeReportSchema = z.object({
  pages: z.array(z.object({ slug: z.string(), kind: z.string(), status: z.number() })),
  sitemapCheck: z.object({ portfolioOrder: z.array(z.string()).nullable().optional() }).nullable().optional(),
});

const OverridesSchema = z.object({
  projects: z
    .record(
      z.string(),
      z.object({
        category: CategorySchema.nullable().optional(),
        categoryNote: z.string().nullable().optional(),
        cover: z.string().optional(),
        published: z.boolean().optional(),
        captions: z.record(z.string(), z.string().nullable()).optional(),
      }),
    )
    .optional(),
  home: z
    .object({
      hero: ImageRefSchema.nullable().optional(),
      manifesto: ImageRefSchema.nullable().optional(),
      materials: z.array(MaterialSchema).optional(),
      pressConfirmed: z.boolean().optional(),
    })
    .optional(),
  site: z.object({ showPricing: z.boolean().optional() }).optional(),
});
type Overrides = z.infer<typeof OverridesSchema>;

const AltOverridesSchema = z.record(
  z.string(),
  z.object({ alt: z.string().min(1), caption: z.string().nullable().optional(), note: z.string().optional() }),
);
type AltOverrides = z.infer<typeof AltOverridesSchema>;

// ----------------------------------------------------------------------------
// Manifest (idempotency)
// ----------------------------------------------------------------------------

interface ManifestOutput {
  kind: "webp" | "og";
  path: string;
  width: number;
  height: number;
  bytes: number;
  settingsHash: string;
  blurDataURL?: string;
}
interface ManifestEntry {
  rawPath: string;
  rawSha1: string;
  settingsHash: string;
  originalWidth: number | null;
  originalHeight: number | null;
  outputs: ManifestOutput[];
}
type Manifest = Record<string, ManifestEntry>;

const ManifestSchema = z.record(
  z.string(),
  z.object({
    rawPath: z.string(),
    rawSha1: z.string(),
    settingsHash: z.string(),
    originalWidth: z.number().nullable(),
    originalHeight: z.number().nullable(),
    outputs: z.array(
      z.object({
        kind: z.enum(["webp", "og"]),
        path: z.string(),
        width: z.number(),
        height: z.number(),
        bytes: z.number(),
        settingsHash: z.string(),
        blurDataURL: z.string().optional(),
      }),
    ),
  }),
);

// ----------------------------------------------------------------------------
// Small helpers
// ----------------------------------------------------------------------------

async function fileExists(file: string): Promise<boolean> {
  try {
    return (await stat(file)).isFile();
  } catch {
    return false;
  }
}

async function fileSize(file: string): Promise<number> {
  try {
    return (await stat(file)).size;
  } catch {
    return 0;
  }
}

async function sha1File(file: string): Promise<string> {
  const hash = createHash("sha1");
  for await (const chunk of createReadStream(file)) hash.update(chunk as Buffer);
  return hash.digest("hex");
}

async function readJson(file: string): Promise<unknown> {
  return JSON.parse(await readFile(file, "utf8")) as unknown;
}

async function readJsonOptional(file: string): Promise<unknown | undefined> {
  if (!(await fileExists(file))) return undefined;
  return readJson(file);
}

const rel = (abs: string) => path.relative(ROOT, abs);
const pad2 = (n: number) => String(n).padStart(2, "0");
/** "6af838_707a3b…" → "707a3b…" (ImageSchema.file forbids "_" in path segments). */
const hexOf = (mediaId: string) => mediaId.replace(/^[0-9a-f]{6}_/, "");
const FILENAME_RE = /\.(jpe?g|png|gif|webp|avif|tiff?|heic)$/i;
const TODO_RE = /\{\{TODO/;

function formatIssues(issues: { path: PropertyKey[]; message: string }[]): string {
  return issues.map((i) => `  ${i.path.map(String).join(".") || "<root>"}: ${i.message}`).join("\n");
}

function parseOrThrow<T>(schema: z.ZodType<T>, value: unknown, what: string): T {
  const res = schema.safeParse(value);
  if (!res.success) throw new Error(`${what} is invalid:\n${formatIssues(res.error.issues)}`);
  return res.data;
}

// ----------------------------------------------------------------------------
// Run state
// ----------------------------------------------------------------------------

interface Summary {
  converted: number;
  skipped: number;
  ogWritten: number;
  rawBytes: number;
  webpBytes: number;
  ogBytes: number;
  diffs: string[];
  warnings: string[];
  contactSheets: string[];
  filesWritten: string[];
}

const summary: Summary = {
  converted: 0,
  skipped: 0,
  ogWritten: 0,
  rawBytes: 0,
  webpBytes: 0,
  ogBytes: 0,
  diffs: [],
  warnings: [],
  contactSheets: [],
  filesWritten: [],
};

const warned = new Set<string>();
const warn = (msg: string) => {
  if (warned.has(msg)) return;
  warned.add(msg);
  log.warn(msg);
  summary.warnings.push(msg);
};

/** Log a difference between scraped text and the previous projects.json value (scraped wins). */
function compare(label: string, scraped: unknown, previous: unknown): void {
  if (previous === undefined) return;
  if (JSON.stringify(scraped) === JSON.stringify(previous)) return;
  const msg = `${label}: scraped value differs from the previous projects.json — keeping scraped. previous=${JSON.stringify(previous)} scraped=${JSON.stringify(scraped)}`;
  log.info(msg);
  summary.diffs.push(msg);
}

// ----------------------------------------------------------------------------
// Conversions
// ----------------------------------------------------------------------------

interface MasterResult {
  width: number;
  height: number;
  bytes: number;
  blurDataURL: string;
  originalWidth: number | null;
  originalHeight: number | null;
}

interface Converter {
  master(mediaId: string, rawAbs: string, outAbs: string, force: boolean): Promise<MasterResult>;
  og(mediaId: string, rawAbs: string, outAbs: string, force: boolean): Promise<{ bytes: number }>;
}

function createConverter(manifest: Manifest): Converter {
  const limit = pLimit(3);
  const shaCache = new Map<string, Promise<string>>();
  const rawSha = (file: string) => {
    let p = shaCache.get(file);
    if (!p) {
      p = sha1File(file);
      shaCache.set(file, p);
    }
    return p;
  };

  const entryFor = async (mediaId: string, rawAbs: string): Promise<{ entry: ManifestEntry; fresh: boolean }> => {
    const sha = await rawSha(rawAbs);
    const existing = manifest[mediaId];
    if (existing && existing.rawSha1 === sha && existing.settingsHash === MASTER_HASH) return { entry: existing, fresh: false };
    const entry: ManifestEntry = {
      rawPath: rel(rawAbs),
      rawSha1: sha,
      settingsHash: MASTER_HASH,
      originalWidth: existing && existing.rawSha1 === sha ? existing.originalWidth : null,
      originalHeight: existing && existing.rawSha1 === sha ? existing.originalHeight : null,
      // keep outputs from the same raw (they are re-validated per output settings hash)
      outputs: existing && existing.rawSha1 === sha ? existing.outputs : [],
    };
    manifest[mediaId] = entry;
    return { entry, fresh: true };
  };

  const upsertOutput = (entry: ManifestEntry, out: ManifestOutput) => {
    entry.outputs = entry.outputs.filter((o) => !(o.kind === out.kind && o.path === out.path));
    entry.outputs.push(out);
  };

  const originalDims = async (entry: ManifestEntry, rawAbs: string) => {
    if (entry.originalWidth && entry.originalHeight) return;
    try {
      const meta = await sharp(rawAbs, { limitInputPixels: false }).metadata();
      const swap = (meta.orientation ?? 1) >= 5;
      entry.originalWidth = (swap ? meta.height : meta.width) ?? null;
      entry.originalHeight = (swap ? meta.width : meta.height) ?? null;
    } catch (err) {
      warn(`metadata() failed for ${rel(rawAbs)}: ${errorMessage(err)}`);
    }
  };

  return {
    master: (mediaId, rawAbs, outAbs, force) =>
      limit(async () => {
        const { entry } = await entryFor(mediaId, rawAbs);
        const outRel = rel(outAbs);
        const cached = entry.outputs.find((o) => o.kind === "webp" && o.path === outRel);
        if (!force && cached && cached.settingsHash === MASTER_HASH && cached.blurDataURL && (await fileExists(outAbs))) {
          summary.skipped++;
          log.debug(`skip (up to date) ${outRel}`);
          return {
            width: cached.width,
            height: cached.height,
            bytes: cached.bytes,
            blurDataURL: cached.blurDataURL,
            originalWidth: entry.originalWidth,
            originalHeight: entry.originalHeight,
          };
        }
        const t0 = Date.now();
        await originalDims(entry, rawAbs);
        await mkdir(path.dirname(outAbs), { recursive: true });
        const { data, info } = await sharp(rawAbs, { limitInputPixels: false })
          .rotate()
          .resize({ width: SETTINGS.master.maxEdge, height: SETTINGS.master.maxEdge, fit: "inside", withoutEnlargement: true })
          .webp({ quality: SETTINGS.master.quality, effort: SETTINGS.master.effort })
          .toBuffer({ resolveWithObject: true });
        await writeFile(outAbs, data);
        const blur = await sharp(data).resize({ width: SETTINGS.blur.width }).webp({ quality: SETTINGS.blur.quality }).toBuffer();
        const blurDataURL = `data:image/webp;base64,${blur.toString("base64")}`;
        const out: ManifestOutput = {
          kind: "webp",
          path: outRel,
          width: info.width,
          height: info.height,
          bytes: info.size,
          settingsHash: MASTER_HASH,
          blurDataURL,
        };
        upsertOutput(entry, out);
        summary.converted++;
        summary.filesWritten.push(outRel);
        log.info(`wrote ${outRel} ${info.width}x${info.height} ${(info.size / 1024).toFixed(0)} KB (${Date.now() - t0} ms)`);
        return {
          width: info.width,
          height: info.height,
          bytes: info.size,
          blurDataURL,
          originalWidth: entry.originalWidth,
          originalHeight: entry.originalHeight,
        };
      }),
    og: (mediaId, rawAbs, outAbs, force) =>
      limit(async () => {
        const { entry } = await entryFor(mediaId, rawAbs);
        const outRel = rel(outAbs);
        const cached = entry.outputs.find((o) => o.kind === "og" && o.path === outRel);
        if (!force && cached && cached.settingsHash === OG_HASH && (await fileExists(outAbs))) {
          log.debug(`skip (up to date) ${outRel}`);
          return { bytes: cached.bytes };
        }
        await mkdir(path.dirname(outAbs), { recursive: true });
        const info = await sharp(rawAbs, { limitInputPixels: false })
          .rotate()
          .resize(SETTINGS.og.width, SETTINGS.og.height, { fit: "cover", position: sharp.strategy.attention })
          .jpeg({ quality: SETTINGS.og.quality, mozjpeg: true })
          .toFile(outAbs);
        upsertOutput(entry, { kind: "og", path: outRel, width: info.width, height: info.height, bytes: info.size, settingsHash: OG_HASH });
        summary.ogWritten++;
        summary.filesWritten.push(outRel);
        log.info(`wrote ${outRel} ${info.width}x${info.height} ${(info.size / 1024).toFixed(0)} KB`);
        return { bytes: info.size };
      }),
  };
}

// ----------------------------------------------------------------------------
// Alt / caption resolution
// ----------------------------------------------------------------------------

/** warmup caption = title || alt, ignoring empty strings and raw file names ("Photo.jpeg"). */
function warmupCaption(img: ScrapeImage): string | null {
  const raw = (img.caption ?? "").trim() || (img.alt ?? "").trim();
  if (!raw) return null;
  if (FILENAME_RE.test(raw)) {
    warn(`caption for ${img.mediaId} looks like a file name ("${raw}") — not used as alt text`);
    return null;
  }
  return raw;
}

function resolveAlt(altOverrides: AltOverrides, img: ScrapeImage, where: string): string {
  const ov = altOverrides[img.mediaId];
  if (ov?.alt && ov.alt.trim()) return ov.alt.trim();
  const cap = warmupCaption(img);
  if (cap) return cap;
  return `{{TODO: alt text for ${where} (${img.mediaId})}}`;
}

function resolveCaption(altOverrides: AltOverrides, overrides: Overrides, slug: string | null, img: ScrapeImage): string | null {
  const ov = altOverrides[img.mediaId];
  if (ov && "caption" in ov && ov.caption !== undefined) return ov.caption;
  const captions = slug ? overrides.projects?.[slug]?.captions : undefined;
  if (captions && Object.prototype.hasOwnProperty.call(captions, img.mediaId)) return captions[img.mediaId] ?? null;
  return warmupCaption(img);
}

// ----------------------------------------------------------------------------
// Projects
// ----------------------------------------------------------------------------

interface BuildContext {
  args: Args;
  converter: Converter;
  overrides: Overrides;
  altOverrides: AltOverrides;
  previous: ProjectsFile | null;
}

interface BuiltProject {
  project: Project;
  /** raw path per built image (parallel to project.images) — used for OG generation */
  raws: string[];
}

async function buildProject(ctx: BuildContext, page: ScrapePage, order: number): Promise<BuiltProject> {
  const slug = page.slug;
  const prev = ctx.previous?.projects.find((p) => p.slug === slug);
  const ov = ctx.overrides.projects?.[slug];
  const force = ctx.args.force && (!ctx.args.only || ctx.args.only === slug);

  const title = page.text.h1[0]?.trim() || prev?.title || "";
  if (!page.text.h1[0]?.trim()) warn(`${slug}: no <h1> scraped; using previous title "${title}"`);
  compare(`projects.${slug}.title`, title, prev?.title);

  const description = page.description?.chosen?.trim() || page.text.meta.description?.trim() || prev?.description || "";
  if (!description) warn(`${slug}: no description scraped or previously recorded`);
  compare(`projects.${slug}.description`, description, prev?.description);

  // category
  let category: Project["category"] = null;
  let categorySource: Project["categorySource"] = "none";
  if (ov && "category" in ov && ov.category !== undefined) {
    category = ov.category;
    categorySource = "override";
  } else if (page.text.category) {
    const parsed = CategorySchema.safeParse(page.text.category.trim());
    if (parsed.success) {
      category = parsed.data;
      categorySource = "site";
    } else warn(`${slug}: scraped category "${page.text.category}" is not one of ${CategorySchema.options.join("/")} — ignored`);
  }
  const categoryNote = ov?.categoryNote ?? null;
  compare(`projects.${slug}.category`, category, prev?.category);
  compare(`projects.${slug}.categoryNote`, categoryNote, prev?.categoryNote);

  // images (page order; only cover|gallery roles belong to a project)
  const candidates = [...page.images].sort((a, b) => a.index - b.index);
  const jobs: { img: ScrapeImage; role: ProjectImage["role"]; rawAbs: string; nn: string; outAbs: string }[] = [];
  for (const img of candidates) {
    if (img.role !== "cover" && img.role !== "gallery") {
      warn(`${slug}: image ${img.mediaId} has role "${img.role}" — not a project image, skipped`);
      continue;
    }
    if (!img.download) {
      warn(`${slug}: image ${img.mediaId} (index ${img.index}) was not downloaded — omitted (nothing invented)`);
      continue;
    }
    const rawAbs = path.join(ROOT, img.download.path);
    if (!(await fileExists(rawAbs))) {
      warn(`${slug}: raw file missing ${img.download.path} — image ${img.mediaId} omitted`);
      continue;
    }
    const nn = pad2(img.index);
    jobs.push({ img, role: img.role, rawAbs, nn, outAbs: path.join(PUBLIC_DIR, "projects", slug, `${nn}-${hexOf(img.mediaId)}.webp`) });
  }
  // Promise.all keeps page order regardless of conversion concurrency.
  const images: ProjectImage[] = await Promise.all(
    jobs.map(async ({ img, role, rawAbs, nn, outAbs }): Promise<ProjectImage> => {
      const m = await ctx.converter.master(img.mediaId, rawAbs, outAbs, force);
      const rawBytes = await fileSize(rawAbs); // await first: `x += await y` would read x before the await
      summary.rawBytes += rawBytes;
      summary.webpBytes += m.bytes;
      return {
        file: `/projects/${slug}/${nn}-${hexOf(img.mediaId)}.webp`,
        mediaId: img.mediaId,
        sourceUrl: img.sourceUrl,
        width: m.width,
        height: m.height,
        originalWidth: m.originalWidth ?? img.originalWidth ?? img.download?.width ?? m.width,
        originalHeight: m.originalHeight ?? img.originalHeight ?? img.download?.height ?? m.height,
        blurDataURL: m.blurDataURL,
        alt: resolveAlt(ctx.altOverrides, img, `${slug} image ${nn}`),
        caption: resolveCaption(ctx.altOverrides, ctx.overrides, slug, img),
        focalPoint: img.focalPoint,
        role,
        source: img.source === "dom-only" ? "dom-only" : "warmup",
      };
    }),
  );
  const raws = jobs.map((j) => j.rawAbs);
  if (!images.length) warn(`${slug}: no images (page had ${page.images.length} records)`);

  // cover
  let cover: number | null = null;
  if (ov?.cover) {
    const i = images.findIndex((im) => im.mediaId === ov.cover);
    if (i >= 0) cover = i;
    else warn(`${slug}: overrides cover ${ov.cover} is not among the project's images — falling back to the cover gallery item`);
  }
  if (cover === null) {
    const i = images.findIndex((im) => im.role === "cover");
    cover = i >= 0 ? i : images.length ? 0 : null;
  }

  const project: Project = {
    slug,
    title,
    category,
    categorySource,
    categoryNote,
    description,
    sourceUrl: page.url,
    order,
    cover,
    published: ov?.published ?? true,
    images,
  };
  return { project, raws };
}

// ----------------------------------------------------------------------------
// Home / portfolio / blog / consultations / site
// ----------------------------------------------------------------------------

const contentBlocks = (page: ScrapePage): TextBlock[] => page.text.textBlocks.filter((b) => !b.inHeader && !b.inFooter);
const footerBlocks = (page: ScrapePage): TextBlock[] => page.text.textBlocks.filter((b) => b.inFooter);

/** Split a paragraph into sentences at ". " / "! " / "? " followed by an upper-case letter or quote. */
function sentences(text: string): string[] {
  return text
    .split(/(?<=[.!?])\s+(?=[A-Z"“‘'])/)
    .map((s) => s.trim())
    .filter(Boolean);
}

function buildMeetTheDesigner(home: ScrapePage, prev: ProjectsFile | null, pressConfirmed: boolean, portrait: SiteImage | null) {
  const previous = prev?.home.meetTheDesigner;
  const blocks = contentBlocks(home);
  const hi = blocks.findIndex((b) => /^h[1-6]$/.test(b.tag) && /meet the designer/i.test(b.text));
  let heading = previous?.heading ?? "";
  let role = previous?.role ?? "";
  let name = previous?.name ?? "";
  let bio: string[] = previous?.bio ?? [];
  let pressMention: string | null = previous?.pressMention ?? null;
  if (hi < 0) warn("home: 'Meet the Designer' heading not found — using previous values");
  else {
    heading = blocks[hi]!.text.trim();
    const ps: TextBlock[] = [];
    for (let i = hi + 1; i < blocks.length; i++) {
      const b = blocks[i]!;
      if (/^h[1-6]$/.test(b.tag)) break;
      if (b.tag === "p" && b.text.trim()) ps.push(b);
    }
    const roleIdx = ps.findIndex((b) => /^[^:]{2,40}:\s*\S/.test(b.text));
    if (roleIdx >= 0) {
      const m = /^([^:]+):\s*(.+)$/.exec(ps[roleIdx]!.text.trim());
      role = (m?.[1] ?? "").trim();
      name = (m?.[2] ?? "").trim();
    } else warn("home: 'Role: Name' line not found in the Meet the Designer block — using previous values");
    bio = [];
    pressMention = null;
    ps.forEach((b, i) => {
      if (i === roleIdx) return;
      const text = b.text.trim();
      if (!pressMention && /featured in/i.test(text)) {
        const parts = sentences(text);
        const idx = parts.findIndex((s) => /featured in/i.test(s));
        if (idx >= 0) {
          pressMention = parts[idx]!;
          const rest = parts.filter((_, j) => j !== idx).join(" ");
          if (rest) bio.push(rest);
          return;
        }
      }
      bio.push(text);
    });
  }
  compare("home.meetTheDesigner.heading", heading, previous?.heading);
  compare("home.meetTheDesigner.role", role, previous?.role);
  compare("home.meetTheDesigner.name", name, previous?.name);
  compare("home.meetTheDesigner.bio", bio, previous?.bio);
  compare("home.meetTheDesigner.pressMention", pressMention, previous?.pressMention);
  return { heading, role, name, bio, pressMention, pressConfirmed, portrait };
}

type LiveCard = ProjectsFile["home"]["liveCards"][number];

/** The three category cards: label / title / body triplets between "Our Recent Projects" and the next h2. */
function buildLiveCards(home: ScrapePage, prev: ProjectsFile | null): LiveCard[] {
  const previous = prev?.home.liveCards;
  const blocks = contentBlocks(home);
  const hi = blocks.findIndex((b) => b.tag === "h2" && /recent projects/i.test(b.text));
  const fallback = () => {
    warn("home: could not parse the three category cards — using previous liveCards");
    return previous ?? [];
  };
  if (hi < 0) return fallback();
  const ps: TextBlock[] = [];
  for (let i = hi + 1; i < blocks.length; i++) {
    const b = blocks[i]!;
    if (/^h[1-6]$/.test(b.tag)) break;
    if (b.tag === "p" && b.text.trim()) ps.push(b);
  }
  // A card starts whenever y stops increasing (label above title above body).
  const groups: TextBlock[][] = [];
  for (const b of ps) {
    const cur = groups[groups.length - 1];
    if (!cur || (cur[cur.length - 1]?.y ?? -1) >= b.y) groups.push([b]);
    else cur.push(b);
  }
  if (groups[0] && groups[0].length === 4) {
    log.info(`home: dropping section subtitle "${groups[0][0]!.text}" before the category cards`);
    groups[0] = groups[0].slice(1);
  }
  if (!groups.length || groups.some((g) => g.length !== 3)) return fallback();
  const cards = groups.map((g) => ({ label: g[0]!.text.trim(), title: g[1]!.text.trim(), body: g[2]!.text.trim() }));
  compare("home.liveCards", cards, previous);
  return cards;
}

function buildPortfolio(page: ScrapePage | null, prev: ProjectsFile | null): ProjectsFile["portfolio"] {
  const previous = prev?.portfolio;
  if (!page) {
    warn("portfolio: page not scraped — using previous values");
    return previous ?? { title: "", intro: "" };
  }
  const title = page.text.h1[0]?.trim() || previous?.title || "";
  const intro = contentBlocks(page).find((b) => b.tag === "p" && b.text.trim())?.text.trim() || previous?.intro || "";
  compare("portfolio.title", title, previous?.title);
  compare("portfolio.intro", intro, previous?.intro);
  return { title, intro };
}

type BodyBlock = { type: "h2" | "h3" | "p" | "li"; text: string };

/** Post body → schema blocks: drop the h1 + date/read-time meta items, Wix's duplicated li→p pairs and a title echo. */
function normalizeBody(post: NonNullable<ScrapePage["text"]["post"]>, title: string, slug: string): BodyBlock[] | null {
  const out: BodyBlock[] = [];
  const metaTexts = new Set([post.date, post.readTime].filter((s): s is string => !!s).map((s) => s.trim()));
  let dropped = 0;
  for (const raw of post.blocks) {
    const text = raw.text.replace(/\s+/g, " ").trim();
    if (!text) continue;
    const tag = raw.tag.toLowerCase();
    if (tag === "h1") continue;
    if (tag === "li" && metaTexts.has(text)) continue;
    let type: BodyBlock["type"];
    if (tag === "h2" || tag === "h3" || tag === "p" || tag === "li") type = tag;
    else if (/^h[4-6]$/.test(tag)) type = "h3";
    else type = "p";
    const last = out[out.length - 1];
    if (type === "p" && last?.type === "li" && last.text === text) {
      dropped++;
      continue;
    }
    if (type === "p" && text === title.trim() && out.length === 0) {
      log.info(`blog/${slug}: dropping a body paragraph that repeats the title`);
      continue;
    }
    out.push({ type, text });
  }
  if (dropped) log.debug(`blog/${slug}: dropped ${dropped} paragraph(s) duplicating list items`);
  return out.length ? out : null;
}

function isoDate(s: string | null | undefined): string | null {
  if (!s) return null;
  const t = Date.parse(s);
  if (Number.isNaN(t)) return null;
  return new Date(t).toISOString();
}

async function buildBlog(
  ctx: BuildContext,
  blogPage: ScrapePage | null,
  posts: ScrapePage[],
): Promise<{ blog: ProjectsFile["blog"]; raws: { slug: string; raw: string }[] }> {
  const blog: ProjectsFile["blog"] = [];
  const raws: { slug: string; raw: string }[] = [];
  const cards = blogPage?.text.blogCards ?? [];
  if (!cards.length) warn("blog: no blog cards scraped — blog[] will be empty");
  const coverByPost = new Map<string, ScrapeImage>();
  for (const img of blogPage?.images ?? []) if (img.role === "blog-cover" && img.postSlug) coverByPost.set(img.postSlug, img);
  for (const p of posts) for (const img of p.images) if (img.role === "blog-cover" && img.postSlug && !coverByPost.has(img.postSlug)) coverByPost.set(img.postSlug, img);

  for (const card of cards) {
    const m = /\/post\/([^/?#]+)/.exec(card.href);
    if (!m?.[1]) {
      warn(`blog: card "${card.title}" has no /post/ slug in ${card.href} — skipped`);
      continue;
    }
    const slug = m[1];
    const post = posts.find((p) => p.url.endsWith(`/post/${slug}`)) ?? null;
    const prev = ctx.previous?.blog.find((b) => b.slug === slug);
    const title = post?.text.h1[0]?.trim() || post?.text.post?.title?.trim() || card.title.trim();
    const excerpt = (card.excerpt ?? "").trim() || prev?.excerpt || "";
    if (!excerpt) warn(`blog/${slug}: no excerpt scraped`);
    const readTime = post?.text.post?.readTime?.trim() || card.readTime?.trim() || null;
    const author = post?.text.post?.author?.trim() || card.author?.trim() || prev?.author || "";
    if (!author) warn(`blog/${slug}: no author scraped`);
    const publishedAt = isoDate(post?.text.meta.publishedTime) ?? isoDate(post?.text.post?.date ?? card.date) ?? prev?.publishedAt ?? "";
    if (!publishedAt) warn(`blog/${slug}: no publish date`);

    let cover: SiteImage | null = null;
    const img = coverByPost.get(slug);
    if (img?.download) {
      const rawAbs = path.join(ROOT, img.download.path);
      if (await fileExists(rawAbs)) {
        const outAbs = path.join(PUBLIC_DIR, "blog", `${slug}.webp`);
        const force = ctx.args.force && (!ctx.args.only || ctx.args.only === "blog");
        const mres = await ctx.converter.master(img.mediaId, rawAbs, outAbs, force);
        const rawBytes = await fileSize(rawAbs);
        summary.rawBytes += rawBytes;
        summary.webpBytes += mres.bytes;
        raws.push({ slug, raw: rawAbs });
        const withTitleAlt: ScrapeImage = { ...img, caption: img.caption ?? (img.alt || null) ?? title };
        cover = {
          file: `/blog/${slug}.webp`,
          mediaId: img.mediaId,
          sourceUrl: img.sourceUrl,
          width: mres.width,
          height: mres.height,
          originalWidth: mres.originalWidth ?? img.originalWidth ?? mres.width,
          originalHeight: mres.originalHeight ?? img.originalHeight ?? mres.height,
          blurDataURL: mres.blurDataURL,
          alt: resolveAlt(ctx.altOverrides, withTitleAlt, `blog cover ${slug}`),
          caption: resolveCaption(ctx.altOverrides, ctx.overrides, null, { ...img, caption: null, alt: null }),
          focalPoint: img.focalPoint,
        };
      } else warn(`blog/${slug}: cover raw file missing ${img.download.path}`);
    } else warn(`blog/${slug}: no downloaded cover`);

    const body = post?.text.post ? normalizeBody(post.text.post, title, slug) : null;
    if (!body) warn(`blog/${slug}: post body not scraped — body is null`);

    blog.push({ slug, title, excerpt, readTime, publishedAt, author, sourceUrl: card.href, cover, body });
  }
  return { blog, raws };
}

function buildConsultations(page: ScrapePage | null, prev: ProjectsFile | null): ProjectsFile["consultations"] {
  const previous = prev?.consultations;
  const cards = page?.text.serviceCards ?? [];
  if (!page || !cards.length) {
    warn("book-online: no service cards scraped — using previous consultations");
    return previous ?? [];
  }
  const consultations = cards.map((c) => ({
    name: c.title.trim(),
    duration: (c.duration ?? "").trim(),
    price: c.price?.trim() || null,
    sourceUrl: page.url,
  }));
  for (const c of consultations) if (!c.duration) warn(`book-online: "${c.name}" has no duration`);
  compare("consultations", consultations, previous);
  return consultations;
}

function buildSite(home: ScrapePage, prev: ProjectsFile | null, showPricing: boolean): ProjectsFile["site"] {
  const previous = prev?.site;
  const footer = footerBlocks(home);
  const allText = home.text.textBlocks.map((b) => b.text).join("\n");
  const emailRe = /^[^\s@]+@[^\s@]+\.[a-z]{2,}$/i;
  const emailDisplayed = footer.find((b) => emailRe.test(b.text.trim()))?.text.trim() ?? previous?.emailDisplayed ?? "";
  if (!emailDisplayed) warn("home: no e-mail address found in the footer");
  const mailto = home.text.links?.mailto?.[0]?.replace(/^mailto:/i, "").split("?")[0]?.trim() ?? null;
  const emailMailto = mailto && emailRe.test(mailto) ? mailto : (previous?.emailMailto ?? null);
  const phone = footer.find((b) => /^[+\d][\d\s().-]{6,}$/.test(b.text.trim()))?.text.trim() ?? previous?.phone ?? null;
  let legalName = previous?.legalName ?? null;
  if (legalName && !allText.includes(legalName)) {
    warn(`site.legalName "${legalName}" does not occur in the scraped home copy — kept from the previous file, please verify`);
  } else if (!legalName) {
    const m = /\b(Style My Space (?:Inc\.|LLC|Design))/.exec(allText);
    legalName = m?.[1] ?? null;
  }
  const site = { legalName, emailDisplayed, emailMailto, phone, showPricing };
  compare("site.emailDisplayed", emailDisplayed, previous?.emailDisplayed);
  compare("site.emailMailto", emailMailto, previous?.emailMailto);
  compare("site.phone", phone, previous?.phone);
  return site;
}

// ----------------------------------------------------------------------------
// Todo collection
// ----------------------------------------------------------------------------

function collectTodos(value: unknown, at: string, out: { token: string; path: string }[]): void {
  if (typeof value === "string") {
    if (TODO_RE.test(value)) out.push({ token: value, path: at });
  } else if (Array.isArray(value)) {
    value.forEach((v, i) => collectTodos(v, `${at}[${i}]`, out));
  } else if (value && typeof value === "object") {
    for (const [k, v] of Object.entries(value)) {
      if (at === "" && k === "todos") continue;
      collectTodos(v, at ? `${at}.${k}` : k, out);
    }
  }
}

// ----------------------------------------------------------------------------
// Contact sheets
// ----------------------------------------------------------------------------

async function writeContactSheets(data: ProjectsFile): Promise<void> {
  await mkdir(SHEETS_DIR, { recursive: true });
  const label = (i: number, img: SiteImage) =>
    `${pad2(i)} · ${img.mediaId} · ${img.width}x${img.height} · ${img.alt.length > 64 ? `${img.alt.slice(0, 63)}…` : img.alt}`;
  for (const p of data.projects) {
    if (!p.images.length) continue;
    const images = p.images.map((img, i) => ({ path: path.join(PUBLIC_DIR, img.file), label: label(i, img) }));
    try {
      const res = await makeContactSheet({
        images,
        out: path.join(SHEETS_DIR, `${p.slug}.png`),
        title: `${p.slug} — ${p.images.length} image(s), cover=${p.cover ?? "null"}`,
      });
      summary.contactSheets.push(...res.files.map(rel));
    } catch (err) {
      warn(`contact sheet for ${p.slug} failed: ${errorMessage(err)}`);
    }
  }
  const site: { path: string; label: string }[] = [];
  const portrait = data.home.meetTheDesigner.portrait;
  if (portrait) site.push({ path: path.join(PUBLIC_DIR, portrait.file), label: `portrait · ${label(0, portrait).slice(5)}` });
  data.blog.forEach((b, i) => {
    if (b.cover) site.push({ path: path.join(PUBLIC_DIR, b.cover.file), label: `blog/${b.slug} · ${label(i, b.cover).slice(5)}` });
  });
  if (site.length) {
    try {
      const res = await makeContactSheet({ images: site, out: path.join(SHEETS_DIR, "site.png"), title: `site assets — ${site.length}` });
      summary.contactSheets.push(...res.files.map(rel));
    } catch (err) {
      warn(`site contact sheet failed: ${errorMessage(err)}`);
    }
  }
}

// ----------------------------------------------------------------------------
// Main
// ----------------------------------------------------------------------------

async function loadPage(slug: string): Promise<ScrapePage | null> {
  const file = path.join(PAGES_DIR, `${slug}.json`);
  if (!(await fileExists(file))) return null;
  const page = parseOrThrow(ScrapePageSchema, await readJson(file), rel(file));
  if (page.status !== 200) {
    warn(`${slug}: scraped with HTTP ${page.status} — treated as missing`);
    return null;
  }
  return page;
}

async function main(): Promise<void> {
  const args = parseArgs(process.argv.slice(2));
  const startedAt = Date.now();
  sharp.cache(false);

  // --- inputs -------------------------------------------------------------
  const report = parseOrThrow(ScrapeReportSchema, await readJson(path.join(SCRAPE_DIR, "scrape-report.json")), "scrape-report.json");
  const overrides = parseOrThrow(OverridesSchema, (await readJsonOptional(OVERRIDES_FILE)) ?? {}, "content/overrides.json");
  const altOverrides = parseOrThrow(AltOverridesSchema, (await readJsonOptional(ALT_OVERRIDES_FILE)) ?? {}, "content/alt-overrides.json");
  const manifestRaw = await readJsonOptional(MANIFEST_FILE);
  const manifestParsed = manifestRaw === undefined ? { success: true as const, data: {} } : ManifestSchema.safeParse(manifestRaw);
  if (!manifestParsed.success) warn("image-manifest.json is unreadable — rebuilding it (all images will be reconverted)");
  const manifest: Manifest = manifestParsed.success ? manifestParsed.data : {};

  let previous: ProjectsFile | null = null;
  const prevRaw = await readJsonOptional(CONTENT_FILE);
  if (prevRaw !== undefined) {
    const parsed = ProjectsFileSchema.safeParse(prevRaw);
    if (parsed.success) previous = parsed.data;
    else warn("existing content/projects.json does not validate — text fallbacks unavailable");
  }

  const home = await loadPage("home");
  if (!home) throw new Error("content/scrape/pages/home.json is missing — run pnpm content:scrape first");
  const portfolio = await loadPage("portfolio");
  const blogPage = await loadPage("blog");
  const bookOnline = await loadPage("book-online");
  const projectSlugs = report.pages.filter((p) => p.kind === "project").map((p) => p.slug);
  const postSlugs = report.pages.filter((p) => p.kind === "post").map((p) => p.slug);
  const posts = (await Promise.all(postSlugs.map(loadPage))).filter((p): p is ScrapePage => p !== null);
  if (args.only && !projectSlugs.includes(args.only) && args.only !== "blog" && args.only !== "site") {
    throw new Error(`--only=${args.only} is not a scraped project slug (${projectSlugs.join(", ")}), "blog" or "site"`);
  }

  // Portfolio order: /portfolio grid (cover mediaId → slug), else the scrape report's portfolioOrder, else scrape order.
  const pages = new Map<string, ScrapePage>();
  for (const slug of projectSlugs) {
    const page = await loadPage(slug);
    if (page) pages.set(slug, page);
    else warn(`${slug}: page JSON missing or not 200 — project omitted`);
  }
  const coverToSlug = new Map<string, string>();
  for (const [slug, page] of pages) for (const img of page.images) if (img.role === "cover") coverToSlug.set(img.mediaId, slug);
  const fromGrid = (portfolio?.images ?? []).map((i) => coverToSlug.get(i.mediaId)).filter((s): s is string => !!s);
  const orderSource = fromGrid.length === pages.size ? fromGrid : (report.sitemapCheck?.portfolioOrder ?? [...pages.keys()]);
  const order = [...new Set([...orderSource.filter((s) => pages.has(s)), ...pages.keys()])];
  if (orderSource !== fromGrid) warn("portfolio: could not derive the project order from the /portfolio grid — using the scrape report order");

  const converter = createConverter(manifest);
  const ctx: BuildContext = { args, converter, overrides, altOverrides, previous };

  // --- projects -----------------------------------------------------------
  const built: BuiltProject[] = [];
  for (const [i, slug] of order.entries()) built.push(await buildProject(ctx, pages.get(slug)!, i));
  const projects = built.map((b) => b.project);
  const rawFor = (ref: ImageRef): string | null => {
    const b = built.find((x) => x.project.slug === ref.slug);
    if (!b) return null;
    const i = b.project.images.findIndex((im) => im.mediaId === ref.mediaId);
    return i >= 0 ? (b.raws[i] ?? null) : null;
  };

  // OG per project (from the cover)
  await Promise.all(
    built.map(async ({ project, raws }) => {
      if (project.cover === null) return;
      const raw = raws[project.cover]!;
      const force = args.force && (!args.only || args.only === project.slug);
      const res = await converter.og(project.images[project.cover]!.mediaId, raw, path.join(PUBLIC_DIR, "projects", project.slug, "og.jpg"), force);
      summary.ogBytes += res.bytes;
    }),
  );

  // --- home refs (overrides) ----------------------------------------------
  const checkRef = (label: string, ref: ImageRef | null | undefined): ImageRef | null => {
    if (!ref) return null;
    if (rawFor(ref)) return ref;
    warn(`${label}: ${ref.slug}/${ref.mediaId} does not resolve to a generated image — set to null`);
    return null;
  };
  const hero = checkRef("home.hero", overrides.home?.hero);
  const manifesto = checkRef("home.manifesto", overrides.home?.manifesto);
  const materials = (overrides.home?.materials ?? []).map((m) => {
    if (m.image && !rawFor(m.image)) {
      throw new Error(`overrides.home.materials[${m.id}].image ${m.image.slug}/${m.image.mediaId} does not resolve to a generated image`);
    }
    return { id: m.id, label: m.label, quote: m.quote, quoteSource: m.quoteSource, image: m.image, objectPosition: m.objectPosition };
  });
  if (!materials.length) warn("home.materials is empty (overrides.home.materials not set)");

  // --- site assets ----------------------------------------------------------
  const forceSite = args.force && (!args.only || args.only === "site");
  const siteAssets: string[] = [];
  if (hero) {
    const raw = rawFor(hero)!;
    const res = await converter.og(hero.mediaId, raw, path.join(PUBLIC_DIR, "site", "og-home.jpg"), forceSite);
    summary.ogBytes += res.bytes;
    siteAssets.push("/site/og-home.jpg");
  } else warn("home.hero is null — public/site/og-home.jpg not generated");

  let portrait: SiteImage | null = null;
  const portraitImg = home.images.find((i) => i.role === "portrait");
  if (portraitImg?.download && (await fileExists(path.join(ROOT, portraitImg.download.path)))) {
    const rawAbs = path.join(ROOT, portraitImg.download.path);
    const outAbs = path.join(PUBLIC_DIR, "site", "portrait.webp");
    const m = await converter.master(portraitImg.mediaId, rawAbs, outAbs, forceSite);
    const rawBytes = await fileSize(rawAbs);
    summary.rawBytes += rawBytes;
    summary.webpBytes += m.bytes;
    portrait = {
      file: "/site/portrait.webp",
      mediaId: portraitImg.mediaId,
      sourceUrl: portraitImg.sourceUrl,
      width: m.width,
      height: m.height,
      originalWidth: m.originalWidth ?? portraitImg.originalWidth ?? m.width,
      originalHeight: m.originalHeight ?? portraitImg.originalHeight ?? m.height,
      blurDataURL: m.blurDataURL,
      alt: resolveAlt(altOverrides, portraitImg, "the designer portrait"),
      caption: resolveCaption(altOverrides, overrides, null, portraitImg),
      focalPoint: portraitImg.focalPoint,
    };
    siteAssets.push("/site/portrait.webp");
  } else warn("home: portrait not downloaded — meetTheDesigner.portrait is null");

  // --- text sections ---------------------------------------------------------
  const headline = home.text.h1[0]?.trim() || previous?.home.headline || "";
  if (!home.text.h1[0]?.trim()) warn("home: no <h1> scraped");
  compare("home.headline", headline, previous?.home.headline);
  const meetTheDesigner = buildMeetTheDesigner(home, previous, overrides.home?.pressConfirmed ?? false, portrait);
  const liveCards = buildLiveCards(home, previous);
  const recentProjects = order.filter((s) => projects.find((p) => p.slug === s)?.published !== false);
  const portfolioData = buildPortfolio(portfolio, previous);
  const { blog } = await buildBlog(ctx, blogPage, posts);
  const consultations = buildConsultations(bookOnline, previous);
  const site = buildSite(home, previous, overrides.site?.showPricing ?? true);

  // --- assemble + validate ---------------------------------------------------
  const data: ProjectsFile = {
    _generated: GENERATED_NOTE,
    generatedAt: new Date().toISOString(),
    source: SITE_URL,
    projects,
    home: { headline, hero, manifesto, materials, meetTheDesigner, liveCards, recentProjects },
    portfolio: portfolioData,
    blog,
    consultations,
    site,
    todos: [],
  };
  const todos: { token: string; path: string }[] = [];
  collectTodos(data, "", todos);
  data.todos = todos;

  const validated = ProjectsFileSchema.safeParse(data);
  if (!validated.success) {
    console.error("content/projects.json would be INVALID — not written:\n" + formatIssues(validated.error.issues));
    process.exitCode = 1;
    await writeFile(MANIFEST_FILE, JSON.stringify(manifest, null, 2) + "\n");
    return;
  }
  await writeFile(CONTENT_FILE, JSON.stringify(data, null, 2) + "\n");
  await writeFile(MANIFEST_FILE, JSON.stringify(manifest, null, 2) + "\n");
  summary.filesWritten.push(rel(CONTENT_FILE), rel(MANIFEST_FILE));

  await writeContactSheets(data);

  // --- report --------------------------------------------------------------
  const perProject = projects.map((p) => ({
    slug: p.slug,
    images: p.images.length,
    cover: p.cover,
    category: p.category,
    todoAlts: p.images.filter((i) => TODO_RE.test(i.alt)).length,
  }));
  log.info(
    `done in ${((Date.now() - startedAt) / 1000).toFixed(1)}s — ${summary.converted} converted, ${summary.skipped} up to date, ${summary.ogWritten} OG written; raw ${(summary.rawBytes / 1048576).toFixed(1)} MB → webp ${(summary.webpBytes / 1048576).toFixed(1)} MB; ${todos.length} TODO token(s)`,
  );
  console.log(
    "SUMMARY " +
      JSON.stringify({
        ok: true,
        projects: perProject,
        siteAssets,
        blog: blog.map((b) => ({ slug: b.slug, cover: b.cover?.file ?? null, body: b.body?.length ?? null })),
        todosTotal: todos.length,
        rawBytes: summary.rawBytes,
        webpBytes: summary.webpBytes,
        ogBytes: summary.ogBytes,
        converted: summary.converted,
        skipped: summary.skipped,
        contactSheets: summary.contactSheets,
        diffs: summary.diffs,
        warnings: summary.warnings,
        filesWritten: summary.filesWritten,
      }),
  );
}

main().catch((err: unknown) => {
  console.error(errorMessage(err));
  process.exit(1);
});
